"""Initial migration

Revision ID: 68e31c6a20e8
Revises: 
Create Date: 2026-06-19 14:45:19.036148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e31c6a20e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_uploads_ck_upload_status')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_uploads_ck_upload_row_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('senior_citizen', sa.Integer(), nullable=False),
    sa.Column('partner', sa.String(length=20), nullable=False),
    sa.Column('dependents', sa.String(length=20), nullable=False),
    sa.Column('tenure', sa.Integer(), nullable=False),
    sa.Column('phone_service', sa.String(length=20), nullable=False),
    sa.Column('multiple_lines', sa.String(length=50), nullable=False),
    sa.Column('internet_service', sa.String(length=50), nullable=False),
    sa.Column('online_security', sa.String(length=50), nullable=False),
    sa.Column('online_backup', sa.String(length=50), nullable=False),
    sa.Column('device_protection', sa.String(length=50), nullable=False),
    sa.Column('tech_support', sa.String(length=50), nullable=False),
    sa.Column('streaming_tv', sa.String(length=50), nullable=False),
    sa.Column('streaming_movies', sa.String(length=50), nullable=False),
    sa.Column('contract', sa.String(length=50), nullable=False),
    sa.Column('paperless_billing', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('monthly_charges', sa.Float(), nullable=False),
    sa.Column('total_charges', sa.Float(), nullable=False),
    sa.Column('churn', sa.String(length=20), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('monthly_charges >= 0.0', name=op.f('ck_customers_ck_customer_monthly_charges')),
    sa.CheckConstraint('senior_citizen IN (0, 1)', name=op.f('ck_customers_ck_customer_senior_citizen')),
    sa.CheckConstraint('total_charges >= 0.0', name=op.f('ck_customers_ck_customer_total_charges')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_customers_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_churn'), 'customers', ['churn'], unique=False)
    op.create_index(op.f('ix_customers_contract'), 'customers', ['contract'], unique=False)
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index('ix_customers_upload_id', 'customers', ['upload_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('top_drivers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('save_plays', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),

    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('churn_probability >= 0.0 AND churn_probability <= 1.0', name=op.f('ck_predictions_ck_prediction_probability')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_predictions_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('customer_id', name=op.f('uq_predictions_customer_id'))
    )
    op.create_index(op.f('ix_predictions_churn_probability'), 'predictions', ['churn_probability'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_is_high_risk'), 'predictions', ['is_high_risk'], unique=False)
    op.create_index('ix_predictions_sorting', 'predictions', ['is_high_risk', 'churn_probability'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_sorting', table_name='predictions')
    op.drop_index(op.f('ix_predictions_is_high_risk'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_churn_probability'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_customers_upload_id', table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_contract'), table_name='customers')
    op.drop_index(op.f('ix_customers_churn'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
